[package]
name = "diesel-aggr-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
diesel = { version = "2.0.0-rc.0", features = ["postgres", "r2d2"] }
